"""add column referece_id to identify question options

Revision ID: 8730ca2c13c6
Revises: bf3b4863e394
Create Date: 2026-01-08 06:38:36.239973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8730ca2c13c6'
down_revision: Union[str, None] = 'bf3b4863e394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.SmallInteger(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.SmallInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
