"""Add type column to users table

Revision ID: b9bd66e387c0
Revises: 
Create Date: 2025-12-18 20:25:19.033962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bd66e387c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("type", sa.String(length=50), nullable=True),
    )

    # 2. Preenche os usuários existentes
    op.execute(
        "UPDATE users SET type = 'user' WHERE type IS NULL"
    )

    # 3. Torna a coluna NOT NULL
    op.alter_column(
        "users",
        "type",
        nullable=False,
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "type")
    # ### end Alembic commands ###
