"""make journey_id from quizz model to nullable true

Revision ID: da23795b1bbd
Revises: 1f3c58594e3a
Create Date: 2025-12-30 19:22:04.349005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da23795b1bbd'
down_revision: Union[str, None] = '1f3c58594e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'journey_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'journey_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
